### ISSUE TITLE
Update for Expo 41

### ISSUE THREAD

**Issue by SimenB** [expo/sentry-expo#184]
### Summary

Using this library in Expo 41 pulls in older versions of the `expo-*` packages. Forcing them to be the recent ones via `resolution` results in deprecation warning.

```
Constants.installationId has been deprecated in favor of generating and storing your own ID. Implement it using expo-application's androidId on Android and a storage API such as expo-secure-store on iOS and localStorage on the web. This API will be removed in SDK 44.
at /Users/simen/repos/monorepo/node_modules/@sentry/utils/dist/instrument.js:111:20 in <anonymous>
at /Users/simen/repos/monorepo/node_modules/expo-constants/build/Constants.js:52:12 in constants.get__installationId
at /Users/simen/repos/monorepo/node_modules/sentry-expo/build/integrations/managed.js:65:22 in ExpoManagedIntegration#setupOnce
at /Users/simen/repos/monorepo/node_modules/@sentry/core/dist/integration.js:51:4 in setupIntegration
at /Users/simen/repos/monorepo/node_modules/@sentry/core/dist/integration.js:66:24 in getIntegrationsToSetup.forEach$argument_0
at [native code]:null in forEach
at /Users/simen/repos/monorepo/node_modules/@sentry/core/dist/integration.js:64:4 in setupIntegrations
at /Users/simen/repos/monorepo/node_modules/@sentry/core/dist/baseclient.js:151:33 in BaseClient.prototype.setupIntegrations
at /Users/simen/repos/monorepo/node_modules/@sentry/hub/dist/hub.js:61:12 in Hub.prototype.bindClient
at /Users/simen/repos/monorepo/node_modules/@sentry/core/dist/sdk.js:17:4 in initAndBind
at /Users/simen/repos/monorepo/node_modules/@sentry/react-native/dist/js/sdk.js:59:4 in init
at /Users/simen/repos/monorepo/node_modules/sentry-expo/build/sentry.js:96:15 in init
at App.tsx:29:0 in <global>
at AppEntry.js:7:0 in <global>
at http://127.0.0.1:19000/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:397811:3 in global code

expo-permissions is now deprecated — the functionality has been moved to other expo packages that directly use these permissions (e.g. expo-location, expo-camera). The package will be removed in the upcoming releases.
at /Users/simen/repos/monorepo/node_modules/@sentry/utils/dist/instrument.js:111:20 in <anonymous>
at /Users/simen/repos/monorepo/node_modules/expo-permissions/build/Permissions.js:41:7 in getAsync
at http://127.0.0.1:19000/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:283065:37 in getAsync
at /Users/simen/repos/monorepo/node_modules/expo-permissions/build/PermissionsHooks.js:32:27 in usePermissions
at /Users/simen/repos/monorepo/node_modules/expo-permissions/build/PermissionsHooks.js:41:8 in useEffect$argument_0
at [native code]:null in performSyncWorkOnRoot
at [native code]:null in dispatchAction
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.0

### Environment

```
  Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - /private/var/folders/gj/0mygpdfn6598xh34njlyrqzc0000gn/T/xfs-e3915fb3/node
      Yarn: 2.4.1 - /private/var/folders/gj/0mygpdfn6598xh34njlyrqzc0000gn/T/xfs-e3915fb3/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 2.21.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```ts
import { init as initSentry } from 'sentry-expo';

initSentry({
  dsn: 'foobar',
  enableInExpoDevelopment: true,
});
```

**Comment by cruzach** [comment]
Will prioritize this update 👍

**Comment by cruzach** [comment]
`sentry-expo@3.1.4` published as next now

sidenote- I think the `expo-permissions` warnings in your stack trace are unrelated to `sentry-expo`

**Comment by SimenB** [comment]
Thanks @cruzach! You seem to have missed `expo-updates`, other than that it looks good 👍 

And you are right about the permission one, I was a bit quick there after looking at the trace 🙂
