### ISSUE TITLE
Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by Rutvik17** [expo/sentry-expo#263]
### Summary

I have a expo managed application and I am getting the following error after installing `sentry-expo` and adding `Sentry.init` to my `App.tsx` file running `unit tests.`

```
● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'bind')

      at Object.utils_2 [as getNativeFetchImplementation] (node_modules/sentry-expo/node_modules/@sentry/react/node_modules/@sentry/src/transports/utils.ts:77:39)
      at new FetchTransport (node_modules/sentry-expo/node_modules/@sentry/react/node_modules/@sentry/src/transports/fetch.ts:14:72)
      at ReactNativeBackend._setupTransport (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/backend.ts:85:12)
      at new BaseBackend (node_modules/sentry-expo/node_modules/@sentry/src/basebackend.ts:79:28)
      at ReactNativeBackend._createSuperInternal (node_modules/sentry-expo/node_modules/@sentry/react-native/dist/js/backend.js:38:311)
      at new ReactNativeBackend (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/backend.ts:18:5)
      at new BaseClient (node_modules/sentry-expo/node_modules/@sentry/src/baseclient.ts:96:21)
      at ReactNativeClient._createSuperInternal (node_modules/sentry-expo/node_modules/@sentry/react-native/dist/js/client.js:26:311)
      at new ReactNativeClient (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/client.ts:21:49)
      at initAndBind (node_modules/sentry-expo/node_modules/@sentry/src/sdk.ts:32:18)
```

My `jest.config.ts` looks like this 
```
import { Config } from "@jest/types";
const untranspiledModulePatterns = [
    "(jest-)?react-native",
    "@react-native",
    "react-native",
    "@react-native-community",
    "expo(nent)?",
    "@expo(nent)?/.*",
    "react-navigation",
    "@react-navigation/.*",
    "@unimodules/.*",
    "unimodules",
    "sentry-expo",
    "native-base",
    "react-native-svg",
    "@sentry/.*",
];

const config: Config.InitialOptions = {
    preset: "jest-expo",
    transformIgnorePatterns: [
        `node_modules/(?!${untranspiledModulePatterns.join("|")})`,
    ],
    moduleFileExtensions: ["ts", "tsx", "js", "jsx"],
};

export default config;
```

`App.tsx`
```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import * as Sentry from 'sentry-expo';
import Constants from 'expo-constants';

Sentry.init({
  dsn: Constants.manifest?.extra?.SENTRY_DSN,
  enableInExpoDevelopment: true,
  debug: true, // If `true`, Sentry will try to print out useful debugging information if something goes wrong with sending the event. Set it to `false` in production
});

export default function App() {
  return (
    <View style={styles.container}>
      <Text testID='hello-world-text'>Hello World!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

`App.test.tsx`
```
import React from 'react';
import { render, screen } from "@testing-library/react-native"

import App from './App';

describe('<App />', () => {
  it('expect hello world is displayed', () => {
    render(<App />);
    const text = screen.getByTestId('hello-world-text')
    expect(text).toEqual('Hello World!');
  });
});
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45.0.0

### Environment

```
expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2022.06.13.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Patch 1 Chipmunk 2021.2.1 Patch 1
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.24 => 0.16.24 
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.11
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. Init a project using the `expo cli`.
2. Install `sentry-expo` and follow other steps using the [sentry-expo docs](https://docs.expo.dev/guides/using-sentry/).
3. Configure the project using `jest` and `typescript`.
4. The test fails with the above error.

**Comment by MiguelNiblock** [comment]
I'm having the same issue
![2022 07 20_05 25-](https://user-images.githubusercontent.com/32658920/180113702-01636856-6e12-4df3-9766-99bb698a0de9.jpeg)
